#pragma once
enum DishType
{
	DT_SALAD_LETTUCE = 0,
	DT_SALAD_LETTUCE_AND_TOMATO,
	DT_SALAD_LETTUCE_TOMATO_AND_CUCUMBER,
	DT_SUSHI_FISH,
	DT_SUSHI_FISH_AND_PRAWN,
	DT_SUSHI_CUCUMBER,
	DT_SUSHI_FISH_AND_CUCUMBER,
	DT_MUSHROOM_BURRITO,
	DT_CHICKEN_BURRITO,
	DT_BEEF_BURRITO,
	DT_COUNT,
};